services:
  - type: web
    name: ecom-api
    runtime: node
    plan: free
    buildCommand:
      - npm install
      - npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
